# Turns compiled SPIR-V modules into one generated C translation unit.
#
# Run in script mode, never included:
#
#   cmake -D"EMBED_INPUTS=a.spv;b.spv" -D"EMBED_NAMES=a;b" \
#         -DEMBED_OUTPUT_C=... -DEMBED_OUTPUT_H=... -P EmbedBinary.cmake
#
# The arrays are uint32_t, not char: vkCreateShaderModule requires four-byte
# alignment for pCode, and a char array gives no such guarantee.

cmake_minimum_required(VERSION 3.16)

if(NOT EMBED_INPUTS OR NOT EMBED_NAMES OR
   NOT EMBED_OUTPUT_C OR NOT EMBED_OUTPUT_H)
    message(FATAL_ERROR
        "EmbedBinary.cmake needs EMBED_INPUTS, EMBED_NAMES, "
        "EMBED_OUTPUT_C and EMBED_OUTPUT_H")
endif()

list(LENGTH EMBED_INPUTS _input_count)
list(LENGTH EMBED_NAMES _name_count)
if(NOT _input_count EQUAL _name_count)
    message(FATAL_ERROR
        "EmbedBinary.cmake: ${_input_count} inputs but ${_name_count} names")
endif()

set(_header "/* Generated by EmbedBinary.cmake. Do not edit or commit. */\n")
string(APPEND _header "#ifndef SNESRECOMP_PLATFORM_VULKAN_SHADERS_H\n")
string(APPEND _header "#define SNESRECOMP_PLATFORM_VULKAN_SHADERS_H\n\n")
string(APPEND _header "#include <stddef.h>\n#include <stdint.h>\n\n")

set(_source "/* Generated by EmbedBinary.cmake. Do not edit or commit. */\n")
string(APPEND _source "#include \"vulkan_shaders.h\"\n\n")

math(EXPR _last "${_input_count} - 1")
foreach(_i RANGE ${_last})
    list(GET EMBED_INPUTS ${_i} _input)
    list(GET EMBED_NAMES ${_i} _name)

    if(NOT EXISTS "${_input}")
        message(FATAL_ERROR "EmbedBinary.cmake: missing SPIR-V ${_input}")
    endif()

    file(READ "${_input}" _hex HEX)
    string(LENGTH "${_hex}" _hex_length)
    math(EXPR _byte_count "${_hex_length} / 2")
    math(EXPR _remainder "${_byte_count} % 4")
    if(NOT _remainder EQUAL 0 OR _byte_count EQUAL 0)
        message(FATAL_ERROR
            "EmbedBinary.cmake: ${_input} is ${_byte_count} bytes, which is "
            "not a non-empty multiple of four, so it is not SPIR-V")
    endif()

    # SPIR-V is little-endian on every platform this backend targets, and the
    # magic number is the cheapest way to catch a truncated or byte-swapped
    # module before a driver reports it as an opaque failure.
    string(SUBSTRING "${_hex}" 0 8 _magic)
    if(NOT _magic STREQUAL "03022307")
        message(FATAL_ERROR
            "EmbedBinary.cmake: ${_input} does not start with the SPIR-V "
            "magic number (found 0x${_magic})")
    endif()

    math(EXPR _word_count "${_byte_count} / 4")
    math(EXPR _last_word "${_word_count} - 1")
    set(_words "")
    foreach(_w RANGE ${_last_word})
        math(EXPR _offset "${_w} * 8")
        string(SUBSTRING "${_hex}" ${_offset} 8 _bytes)
        string(SUBSTRING "${_bytes}" 0 2 _b0)
        string(SUBSTRING "${_bytes}" 2 2 _b1)
        string(SUBSTRING "${_bytes}" 4 2 _b2)
        string(SUBSTRING "${_bytes}" 6 2 _b3)
        list(APPEND _words "0x${_b3}${_b2}${_b1}${_b0}u")
    endforeach()

    string(APPEND _header
        "extern const uint32_t snesrecomp_vulkan_${_name}_spv[${_word_count}];\n")
    string(APPEND _header
        "enum { SNESRECOMP_VULKAN_${_name}_SPV_BYTES = ${_byte_count} };\n\n")

    string(APPEND _source
        "const uint32_t snesrecomp_vulkan_${_name}_spv[${_word_count}] = {\n")
    set(_column 0)
    set(_line "   ")
    foreach(_word IN LISTS _words)
        string(APPEND _line " ${_word},")
        math(EXPR _column "${_column} + 1")
        if(_column EQUAL 6)
            string(APPEND _source "${_line}\n")
            set(_line "   ")
            set(_column 0)
        endif()
    endforeach()
    if(NOT _column EQUAL 0)
        string(APPEND _source "${_line}\n")
    endif()
    string(APPEND _source "};\n\n")
endforeach()

string(APPEND _header "#endif\n")

file(WRITE "${EMBED_OUTPUT_H}" "${_header}")
file(WRITE "${EMBED_OUTPUT_C}" "${_source}")
